"use client";

import { BarChart3, CreditCard, LayoutDashboard, Link2, LogOut, Settings, Users } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, ApiError, json } from "@/lib/api";
import type { Affiliate, Code, Conversion, Overview, Withdrawal } from "@/lib/types";

type View = "overview" | "links" | "conversions" | "payouts" | "settings";
const NAV: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "links", label: "Referral links", icon: Link2 },
  { id: "conversions", label: "Conversions", icon: Users }, { id: "payouts", label: "Payouts", icon: CreditCard },
  { id: "settings", label: "Settings", icon: Settings },
];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
const date = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));

function Login({ onLogin }: { onLogin: (value?: Affiliate) => void }) {
  const [mode, setMode] = useState<"signin" | "register">("signin");
  const [step, setStep] = useState<"details" | "verify" | "password">("details");
  const [email, setEmail] = useState(""); const [name, setName] = useState("");
  const [password, setPassword] = useState(""); const [code, setCode] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const request = async (path: string, body: unknown) => api(path, json(body));
  async function signIn(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await request("/session/login", { email: email.trim(), password }); onLogin(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not sign in."); } finally { setBusy(false); } }
  async function startRegistration(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await request("/session/send", { email: email.trim(), name: name.trim(), purpose: "verify" }); setStep("verify"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not send the verification code."); } finally { setBusy(false); } }
  async function verifyRegistration(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await request("/session/verify", { email: email.trim(), code, purpose: "verify" }); setStep("password"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not verify the code."); } finally { setBusy(false); } }
  async function register(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await request("/session/register", { email: email.trim(), name: name.trim(), password }); onLogin(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create your account."); } finally { setBusy(false); } }
  const switchMode = (next: "signin" | "register") => { setMode(next); setStep("details"); setPassword(""); setCode(""); setError(""); };
  const socialReturn = encodeURIComponent(process.env.NEXT_PUBLIC_AFFILIATE_URL || "https://affiliate.gathos.live");
  return <main className="login-page"><section className="login-panel"><div className="brand"><span>G</span><div><strong>Gathos</strong><small>Affiliate programme</small></div></div>
    <div className="login-card"><p className="eyebrow">Partner access</p><h1>Access your dashboard.</h1><p className="muted">Use the same account and secure session as your Gathos dashboard.</p>
      {step === "details" && <div className="login-tabs"><button className={mode === "signin" ? "active" : ""} onClick={() => switchMode("signin")}>Sign in</button><button className={mode === "register" ? "active" : ""} onClick={() => switchMode("register")}>Create account</button></div>}
      {error && <p className="error">{error}</p>}
      {mode === "signin" && <form onSubmit={signIn}><label>Email address<input autoFocus required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="primary" disabled={busy}>{busy ? "Signing in…" : "Sign in with email"}</button></form>}
      {mode === "register" && step === "details" && <form onSubmit={startRegistration}><label>Your name<input autoFocus required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /></label><button className="primary" disabled={busy}>{busy ? "Sending code…" : "Verify email"}</button></form>}
      {mode === "register" && step === "verify" && <form onSubmit={verifyRegistration}><p className="muted">Enter the six-digit code sent to {email}.</p><label>Verification code<input autoFocus required inputMode="numeric" maxLength={6} pattern="[0-9]{6}" value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ""))} /></label><button className="primary" disabled={busy || code.length !== 6}>{busy ? "Verifying…" : "Verify code"}</button><button type="button" className="text-button" onClick={() => setStep("details")}>Change details</button></form>}
      {mode === "register" && step === "password" && <form onSubmit={register}><p className="muted">Email verified. Create a password with at least eight characters.</p><label>Password<input autoFocus required minLength={8} type="password" autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="primary" disabled={busy}>{busy ? "Creating account…" : "Create account"}</button></form>}
      <div className="login-divider"><span>or</span></div>
      <a className="workos-button" href={`/api/affiliate/session/social?return_to=${socialReturn}`}>
        <span className="social-provider-icons" aria-hidden="true">
          <svg className="social-provider-icon" viewBox="0 0 24 24">
            <path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.5h3.3c1.9-1.8 2.9-4.4 2.9-7.4Z" />
            <path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.5c-.9.6-2.1 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3v2.6A10 10 0 0 0 12 22Z" />
            <path fill="#FBBC05" d="M6.4 14a6 6 0 0 1 0-3.9V7.5H3a10 10 0 0 0 0 9.1L6.4 14Z" />
            <path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.9 1.5l2.9-2.9A9.8 9.8 0 0 0 3 7.5l3.4 2.6A6 6 0 0 1 12 5.9Z" />
          </svg>
          <svg className="social-provider-icon" viewBox="0 0 24 24">
            <path fill="currentColor" d="M17.1 12.6c0-2.8 2.3-4.2 2.4-4.3A5.2 5.2 0 0 0 15.4 6c-1.8-.2-3.4 1-4.3 1s-2.2-1-3.7-1A5.5 5.5 0 0 0 2.8 8.8c-2 3.4-.5 8.4 1.4 11.2.9 1.4 2 2.9 3.5 2.8 1.4-.1 1.9-.9 3.6-.9s2.2.9 3.7.9c1.5 0 2.5-1.4 3.4-2.7a12.2 12.2 0 0 0 1.6-3.3 4.9 4.9 0 0 1-2.9-4.2ZM14.2 4.1A4.9 4.9 0 0 0 15.3.5a5 5 0 0 0-3.3 1.7 4.7 4.7 0 0 0-1.2 3.5 4.1 4.1 0 0 0 3.4-1.6Z" />
          </svg>
          <svg className="social-provider-icon" viewBox="0 0 24 24">
            <path fill="currentColor" d="M12 .7A11.5 11.5 0 0 0 8.4 23c.6.1.8-.3.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.8-1.3-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-5.9 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.2 0 0 1-.3 3.3 1.2a11.3 11.3 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.6 1.7.2 2.9.1 3.2.8.8 1.2 1.9 1.2 3.2 0 4.6-2.8 5.6-5.5 5.9.4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6A11.5 11.5 0 0 0 12 .7Z" />
          </svg>
        </span>
        Login with Social
      </a>
    </div></section><aside className="login-art"><p>PARTNER NETWORK</p><h2>Your audience.<br/><em>Shared momentum.</em></h2><div className="art-stat"><strong>One account</strong><span>shared securely across Gathos dashboards</span></div></aside></main>;
}

export function AffiliatePortal() {
  const [affiliate, setAffiliate] = useState<Affiliate | null>(null); const [overview, setOverview] = useState<Overview | null>(null);
  const [view, setView] = useState<View>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [conversions, setConversions] = useState<Conversion[]>([]); const [withdrawals, setWithdrawals] = useState<Withdrawal[]>([]);
  const load = useCallback(async () => { try { const data = await api<Overview>("/overview"); setAffiliate(data.affiliate); setOverview(data); setError(""); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) setAffiliate(null); else setError(reason instanceof Error ? reason.message : "Could not load dashboard."); } finally { setLoading(false); } }, []);
  // The initial session probe intentionally hydrates client-owned portal state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!affiliate) return; if (view === "conversions") void api<{ conversions: Conversion[] }>("/conversions?limit=200").then(v => setConversions(v.conversions)).catch(e => setError(e.message)); if (view === "payouts") void api<{ withdrawals: Withdrawal[] }>("/withdrawals").then(v => setWithdrawals(v.withdrawals)).catch(e => setError(e.message)); }, [view, affiliate]);
  if (loading) return <div className="splash"><div className="brand-mark">G</div><span>Loading partner workspace…</span></div>;
  if (!affiliate || !overview) return <Login onLogin={() => { setLoading(true); void load(); }} />;
  async function logout() { await api("/auth/logout", json({})); setAffiliate(null); setOverview(null); }
  return <div className="shell"><aside className="sidebar"><div className="brand"><span>G</span><div><strong>Gathos</strong><small>Affiliates</small></div></div><nav>{NAV.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><item.icon />{item.label}</button>)}</nav><div className="side-foot"><div className="avatar">{(affiliate.name || affiliate.email)[0].toUpperCase()}</div><div><strong>{affiliate.name || "Affiliate"}</strong><small>{affiliate.email}</small></div><button aria-label="Sign out" onClick={logout}><LogOut /></button></div></aside>
    <main className="workspace"><header><div><p className="eyebrow">Affiliate dashboard</p><h1>{NAV.find(n => n.id === view)?.label}</h1></div><div className="live"><i/> Attribution active</div></header><section className="content">{error && <div className="notice">{error}</div>}{view === "overview" && <OverviewView data={overview} setView={setView} />}{view === "links" && <LinksView codes={overview.codes} refresh={load} />}{view === "conversions" && <ConversionsView rows={conversions} />}{view === "payouts" && <PayoutsView overview={overview} rows={withdrawals} refresh={async () => { await load(); setWithdrawals((await api<{ withdrawals: Withdrawal[] }>("/withdrawals")).withdrawals); }} />}{view === "settings" && <SettingsView affiliate={affiliate} saved={value => { setAffiliate(value); void load(); }} />}</section></main></div>;
}

function OverviewView({ data, setView }: { data: Overview; setView: (v: View) => void }) { const s = data.stats; const conversionRate = s.total_clicks ? (s.total_referrals / s.total_clicks * 100) : 0; return <><div className="hero-card"><div><p className="eyebrow">Available balance</p><strong>{money(s.wallet_balance)}</strong><span>{money(Math.max(0, s.min_withdrawal - s.wallet_balance))} until the next payout threshold</span></div><button className="primary compact" onClick={() => setView("payouts")}>Manage payouts</button></div><div className="metric-grid">{[["Total earned", money(s.total_earned)], ["Conversions", s.total_conversions], ["Link clicks", s.total_clicks], ["Signup rate", `${conversionRate.toFixed(1)}%`]].map(([label,value]) => <article className="metric" key={label}><p>{label}</p><strong>{value}</strong><small>All-time</small></article>)}</div><div className="split"><article className="card"><div className="card-head"><div><p className="eyebrow">Performance</p><h2>Funnel snapshot</h2></div><BarChart3 /></div><div className="funnel"><div style={{width:"100%"}}><b>{s.total_clicks}</b><span>Clicks</span></div><div style={{width:"74%"}}><b>{s.total_referrals}</b><span>Signups</span></div><div style={{width:"48%"}}><b>{s.total_conversions}</b><span>Paid</span></div></div></article><article className="card"><p className="eyebrow">Quick share</p><h2>Your primary link</h2>{data.codes[0] ? <Share code={data.codes[0]} /> : <p className="muted">Create a referral link to begin.</p>}<button className="secondary" onClick={() => setView("links")}>Manage all links</button></article></div></>; }
function Share({ code }: { code: Code }) { const url = `${process.env.NEXT_PUBLIC_REFERRAL_BASE_URL || "https://gathos.com"}/?ref=${code.code}`; const [copied,setCopied]=useState(false); return <div className="share"><code>{url}</code><button onClick={() => { void navigator.clipboard.writeText(url); setCopied(true); setTimeout(()=>setCopied(false),1500); }}>{copied ? "Copied" : "Copy"}</button></div>; }
function LinksView({ codes, refresh }: { codes: Code[]; refresh: () => Promise<void> }) { const [label,setLabel]=useState(""); const [busy,setBusy]=useState(false); async function create(e:FormEvent){e.preventDefault();setBusy(true);try{await api("/codes",json({label}));setLabel("");await refresh();}finally{setBusy(false);}} async function toggle(row:Code){await api(`/codes/${row.id}`,json({active:!row.is_active},"PATCH"));await refresh();} return <><div className="section-intro"><div><p className="eyebrow">Campaign tools</p><h2>Referral links</h2><p>Use labels to separate channels and compare click performance.</p></div><form className="inline-form" onSubmit={create}><input maxLength={60} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Campaign label"/><button className="primary" disabled={busy || codes.length >= 10}>Create link</button></form></div><div className="card table-card"><table><thead><tr><th>Campaign</th><th>Referral code</th><th>Clicks</th><th>Status</th><th></th></tr></thead><tbody>{codes.map(row=><tr key={row.id}><td><strong>{row.label || "Untitled link"}</strong><small>{date(row.created_at)}</small></td><td><Share code={row}/></td><td>{row.click_count}</td><td><span className={`pill ${row.is_active?"green":"gray"}`}>{row.is_active?"Active":"Retired"}</span></td><td><button className="text-button" onClick={()=>void toggle(row)}>{row.is_active?"Retire":"Restore"}</button></td></tr>)}</tbody></table></div></>; }
function ConversionsView({rows}:{rows:Conversion[]}) { return <div className="card table-card"><div className="card-head"><div><p className="eyebrow">Attributed revenue</p><h2>Conversions</h2></div><span>{rows.length} records</span></div><table><thead><tr><th>Customer</th><th>Campaign</th><th>Plan</th><th>Commission</th><th>Date</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.user_email || "—"}</td><td>{row.affiliate_codes?.label || row.affiliate_codes?.code || "—"}</td><td><span className="pill">{row.plan}</span></td><td><strong>{money(row.commission_usd)}</strong></td><td>{date(row.created_at)}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Conversions will appear after referred customers upgrade.</div>}</div>; }
function PayoutsView({overview,rows,refresh}:{overview:Overview;rows:Withdrawal[];refresh:()=>Promise<void>}) { const [method,setMethod]=useState("paypal"); const [paypal,setPaypal]=useState(""); const [holder,setHolder]=useState(""); const [account,setAccount]=useState(""); const [busy,setBusy]=useState(false); async function request(e:FormEvent){e.preventDefault();setBusy(true);try{const payout_details=method==="paypal"?{method,paypal_email:paypal}:{method,account_holder:holder,account_number:account};await api("/withdrawals",json({payout_details}));await refresh();}finally{setBusy(false);}} return <div className="split payout-grid"><article className="card"><p className="eyebrow">Available</p><h2 className="balance">{money(overview.stats.wallet_balance)}</h2><p className="muted">Requests withdraw the full available balance. Minimum {money(overview.stats.min_withdrawal)}.</p><form onSubmit={request}><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="paypal">PayPal</option><option value="bank">Bank transfer</option></select></label>{method==="paypal"?<label>PayPal email<input required type="email" value={paypal} onChange={e=>setPaypal(e.target.value)}/></label>:<><label>Account holder<input required value={holder} onChange={e=>setHolder(e.target.value)}/></label><label>Account number<input required value={account} onChange={e=>setAccount(e.target.value)}/></label></>}<button className="primary" disabled={busy||!overview.stats.can_withdraw||overview.stats.has_pending_withdrawal}>{overview.stats.has_pending_withdrawal?"Payout pending":busy?"Submitting…":"Request payout"}</button></form></article><article className="card"><div className="card-head"><div><p className="eyebrow">Ledger</p><h2>Payout history</h2></div></div><div className="history">{rows.map(row=><div key={row.id}><div><strong>{money(row.amount)}</strong><small>{date(row.requested_at)} · {row.payout_details.method}</small></div><span className={`pill ${row.status==="paid"?"green":""}`}>{row.status}</span></div>)}{!rows.length&&<div className="empty">No payouts requested yet.</div>}</div></article></div>; }
function SettingsView({affiliate,saved}:{affiliate:Affiliate;saved:(a:Affiliate)=>void}) { const [name,setName]=useState(affiliate.name||""); const [busy,setBusy]=useState(false); async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await api<{affiliate:Affiliate}>("/profile",json({name},"PATCH"));saved(r.affiliate);}finally{setBusy(false);}} return <div className="card settings-card"><p className="eyebrow">Partner profile</p><h2>Account details</h2><form onSubmit={submit}><label>Display name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input disabled value={affiliate.email}/><span>Contact support to change the verified login email.</span></label><button className="primary" disabled={busy}>{busy?"Saving…":"Save changes"}</button></form></div>; }
