"use client";

import { BarChart3, CreditCard, LayoutDashboard, Link2, LogOut, Settings, Users } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, ApiError, json } from "@/lib/api";
import type { Affiliate, Code, Conversion, Overview, Withdrawal } from "@/lib/types";

type View = "overview" | "links" | "conversions" | "payouts" | "settings";
const NAV: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "links", label: "Referral links", icon: Link2 },
  { id: "conversions", label: "Conversions", icon: Users }, { id: "payouts", label: "Payouts", icon: CreditCard },
  { id: "settings", label: "Settings", icon: Settings },
];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
const date = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));

function Login({ onLogin }: { onLogin: (value: Affiliate) => void }) {
  const [step, setStep] = useState<"email" | "code">("email"); const [email, setEmail] = useState("");
  const [code, setCode] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try {
      if (step === "email") { await api("/auth/send-otp", json({ email })); setStep("code"); }
      else { const result = await api<{ affiliate: Affiliate }>("/auth/verify-otp", json({ email, code, name })); onLogin(result.affiliate); }
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not sign in."); } finally { setBusy(false); }
  }
  return <main className="login-page"><section className="login-panel"><div className="brand"><span>G</span><div><strong>Gathos</strong><small>Affiliate programme</small></div></div>
    <div className="login-card"><p className="eyebrow">Partner access</p><h1>{step === "email" ? "Grow with Gathos." : "Check your inbox."}</h1><p className="muted">{step === "email" ? "Sign in or create your affiliate account with a one-time code." : `We sent a six-digit code to ${email}.`}</p>
      <form onSubmit={submit}>{step === "email" ? <label>Email address<input autoFocus required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label> : <><label>Your name <span>(first sign-in only)</span><input value={name} onChange={e => setName(e.target.value)} placeholder="Full name" /></label><label>Verification code<input autoFocus required inputMode="numeric" maxLength={6} pattern="[0-9]{6}" value={code} onChange={e => setCode(e.target.value)} placeholder="000000" /></label></>}
        {error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? "Please wait…" : step === "email" ? "Send sign-in code" : "Open dashboard"}</button>{step === "code" && <button type="button" className="text-button" onClick={() => setStep("email")}>Use another email</button>}</form>
    </div></section><aside className="login-art"><p>PARTNER NETWORK</p><h2>Your audience.<br/><em>Shared momentum.</em></h2><div className="art-stat"><strong>30 days</strong><span>first-touch attribution window</span></div></aside></main>;
}

export function AffiliatePortal() {
  const [affiliate, setAffiliate] = useState<Affiliate | null>(null); const [overview, setOverview] = useState<Overview | null>(null);
  const [view, setView] = useState<View>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [conversions, setConversions] = useState<Conversion[]>([]); const [withdrawals, setWithdrawals] = useState<Withdrawal[]>([]);
  const load = useCallback(async () => { try { const data = await api<Overview>("/overview"); setAffiliate(data.affiliate); setOverview(data); setError(""); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) setAffiliate(null); else setError(reason instanceof Error ? reason.message : "Could not load dashboard."); } finally { setLoading(false); } }, []);
  // The initial session probe intentionally hydrates client-owned portal state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!affiliate) return; if (view === "conversions") void api<{ conversions: Conversion[] }>("/conversions?limit=200").then(v => setConversions(v.conversions)).catch(e => setError(e.message)); if (view === "payouts") void api<{ withdrawals: Withdrawal[] }>("/withdrawals").then(v => setWithdrawals(v.withdrawals)).catch(e => setError(e.message)); }, [view, affiliate]);
  if (loading) return <div className="splash"><div className="brand-mark">G</div><span>Loading partner workspace…</span></div>;
  if (!affiliate || !overview) return <Login onLogin={() => { setLoading(true); void load(); }} />;
  async function logout() { await api("/auth/logout", json({})); setAffiliate(null); setOverview(null); }
  return <div className="shell"><aside className="sidebar"><div className="brand"><span>G</span><div><strong>Gathos</strong><small>Affiliates</small></div></div><nav>{NAV.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><item.icon />{item.label}</button>)}</nav><div className="side-foot"><div className="avatar">{(affiliate.name || affiliate.email)[0].toUpperCase()}</div><div><strong>{affiliate.name || "Affiliate"}</strong><small>{affiliate.email}</small></div><button aria-label="Sign out" onClick={logout}><LogOut /></button></div></aside>
    <main className="workspace"><header><div><p className="eyebrow">Affiliate dashboard</p><h1>{NAV.find(n => n.id === view)?.label}</h1></div><div className="live"><i/> Attribution active</div></header><section className="content">{error && <div className="notice">{error}</div>}{view === "overview" && <OverviewView data={overview} setView={setView} />}{view === "links" && <LinksView codes={overview.codes} refresh={load} />}{view === "conversions" && <ConversionsView rows={conversions} />}{view === "payouts" && <PayoutsView overview={overview} rows={withdrawals} refresh={async () => { await load(); setWithdrawals((await api<{ withdrawals: Withdrawal[] }>("/withdrawals")).withdrawals); }} />}{view === "settings" && <SettingsView affiliate={affiliate} saved={value => { setAffiliate(value); void load(); }} />}</section></main></div>;
}

function OverviewView({ data, setView }: { data: Overview; setView: (v: View) => void }) { const s = data.stats; const conversionRate = s.total_clicks ? (s.total_referrals / s.total_clicks * 100) : 0; return <><div className="hero-card"><div><p className="eyebrow">Available balance</p><strong>{money(s.wallet_balance)}</strong><span>{money(Math.max(0, s.min_withdrawal - s.wallet_balance))} until the next payout threshold</span></div><button className="primary compact" onClick={() => setView("payouts")}>Manage payouts</button></div><div className="metric-grid">{[["Total earned", money(s.total_earned)], ["Conversions", s.total_conversions], ["Link clicks", s.total_clicks], ["Signup rate", `${conversionRate.toFixed(1)}%`]].map(([label,value]) => <article className="metric" key={label}><p>{label}</p><strong>{value}</strong><small>All-time</small></article>)}</div><div className="split"><article className="card"><div className="card-head"><div><p className="eyebrow">Performance</p><h2>Funnel snapshot</h2></div><BarChart3 /></div><div className="funnel"><div style={{width:"100%"}}><b>{s.total_clicks}</b><span>Clicks</span></div><div style={{width:"74%"}}><b>{s.total_referrals}</b><span>Signups</span></div><div style={{width:"48%"}}><b>{s.total_conversions}</b><span>Paid</span></div></div></article><article className="card"><p className="eyebrow">Quick share</p><h2>Your primary link</h2>{data.codes[0] ? <Share code={data.codes[0]} /> : <p className="muted">Create a referral link to begin.</p>}<button className="secondary" onClick={() => setView("links")}>Manage all links</button></article></div></>; }
function Share({ code }: { code: Code }) { const url = `${process.env.NEXT_PUBLIC_REFERRAL_BASE_URL || "https://gathos.com"}/?ref=${code.code}`; const [copied,setCopied]=useState(false); return <div className="share"><code>{url}</code><button onClick={() => { void navigator.clipboard.writeText(url); setCopied(true); setTimeout(()=>setCopied(false),1500); }}>{copied ? "Copied" : "Copy"}</button></div>; }
function LinksView({ codes, refresh }: { codes: Code[]; refresh: () => Promise<void> }) { const [label,setLabel]=useState(""); const [busy,setBusy]=useState(false); async function create(e:FormEvent){e.preventDefault();setBusy(true);try{await api("/codes",json({label}));setLabel("");await refresh();}finally{setBusy(false);}} async function toggle(row:Code){await api(`/codes/${row.id}`,json({active:!row.is_active},"PATCH"));await refresh();} return <><div className="section-intro"><div><p className="eyebrow">Campaign tools</p><h2>Referral links</h2><p>Use labels to separate channels and compare click performance.</p></div><form className="inline-form" onSubmit={create}><input maxLength={60} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Campaign label"/><button className="primary" disabled={busy || codes.length >= 10}>Create link</button></form></div><div className="card table-card"><table><thead><tr><th>Campaign</th><th>Referral code</th><th>Clicks</th><th>Status</th><th></th></tr></thead><tbody>{codes.map(row=><tr key={row.id}><td><strong>{row.label || "Untitled link"}</strong><small>{date(row.created_at)}</small></td><td><Share code={row}/></td><td>{row.click_count}</td><td><span className={`pill ${row.is_active?"green":"gray"}`}>{row.is_active?"Active":"Retired"}</span></td><td><button className="text-button" onClick={()=>void toggle(row)}>{row.is_active?"Retire":"Restore"}</button></td></tr>)}</tbody></table></div></>; }
function ConversionsView({rows}:{rows:Conversion[]}) { return <div className="card table-card"><div className="card-head"><div><p className="eyebrow">Attributed revenue</p><h2>Conversions</h2></div><span>{rows.length} records</span></div><table><thead><tr><th>Customer</th><th>Campaign</th><th>Plan</th><th>Commission</th><th>Date</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.user_email || "—"}</td><td>{row.affiliate_codes?.label || row.affiliate_codes?.code || "—"}</td><td><span className="pill">{row.plan}</span></td><td><strong>{money(row.commission_usd)}</strong></td><td>{date(row.created_at)}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Conversions will appear after referred customers upgrade.</div>}</div>; }
function PayoutsView({overview,rows,refresh}:{overview:Overview;rows:Withdrawal[];refresh:()=>Promise<void>}) { const [method,setMethod]=useState("paypal"); const [paypal,setPaypal]=useState(""); const [holder,setHolder]=useState(""); const [account,setAccount]=useState(""); const [busy,setBusy]=useState(false); async function request(e:FormEvent){e.preventDefault();setBusy(true);try{const payout_details=method==="paypal"?{method,paypal_email:paypal}:{method,account_holder:holder,account_number:account};await api("/withdrawals",json({payout_details}));await refresh();}finally{setBusy(false);}} return <div className="split payout-grid"><article className="card"><p className="eyebrow">Available</p><h2 className="balance">{money(overview.stats.wallet_balance)}</h2><p className="muted">Requests withdraw the full available balance. Minimum {money(overview.stats.min_withdrawal)}.</p><form onSubmit={request}><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="paypal">PayPal</option><option value="bank">Bank transfer</option></select></label>{method==="paypal"?<label>PayPal email<input required type="email" value={paypal} onChange={e=>setPaypal(e.target.value)}/></label>:<><label>Account holder<input required value={holder} onChange={e=>setHolder(e.target.value)}/></label><label>Account number<input required value={account} onChange={e=>setAccount(e.target.value)}/></label></>}<button className="primary" disabled={busy||!overview.stats.can_withdraw||overview.stats.has_pending_withdrawal}>{overview.stats.has_pending_withdrawal?"Payout pending":busy?"Submitting…":"Request payout"}</button></form></article><article className="card"><div className="card-head"><div><p className="eyebrow">Ledger</p><h2>Payout history</h2></div></div><div className="history">{rows.map(row=><div key={row.id}><div><strong>{money(row.amount)}</strong><small>{date(row.requested_at)} · {row.payout_details.method}</small></div><span className={`pill ${row.status==="paid"?"green":""}`}>{row.status}</span></div>)}{!rows.length&&<div className="empty">No payouts requested yet.</div>}</div></article></div>; }
function SettingsView({affiliate,saved}:{affiliate:Affiliate;saved:(a:Affiliate)=>void}) { const [name,setName]=useState(affiliate.name||""); const [busy,setBusy]=useState(false); async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await api<{affiliate:Affiliate}>("/profile",json({name},"PATCH"));saved(r.affiliate);}finally{setBusy(false);}} return <div className="card settings-card"><p className="eyebrow">Partner profile</p><h2>Account details</h2><form onSubmit={submit}><label>Display name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input disabled value={affiliate.email}/><span>Contact support to change the verified login email.</span></label><button className="primary" disabled={busy}>{busy?"Saving…":"Save changes"}</button></form></div>; }
